import type { Metadata } from "next";
import {Montserrat , Cabin} from 'next/font/google'
import "./globals.css";

export const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"],
  display: "swap",
  variable: '--montserrat'
});

export const cabin = Cabin({
  weight: ["400","500","600","700"],
  subsets: ["latin"],
  display: "swap",
  variable: '--cabin'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${cabin.variable} `}>
      <body>{children}</body>
    </html>
  );
}
