export const wordsWithSynonyms = [
  {
    root: "happy",
    part_of_speech: "adjective",
    context_sentence: "I am so happy to see you.",
    synonyms: [
      "joyful",
      "content",
      "ecstatic",
      "blissful",
      "glad",
      "cheerful",
      "satisfied",
      "pleased",
      "elated",
    ],
  },
  {
    root: "sad",
    part_of_speech: "adjective",
    context_sentence: "She felt sad after hearing the news.",
    synonyms: [
      "melancholy",
      "gloomy",
      "sorrowful",
      "unhappy",
      "despondent",
      "dejected",
      "downcast",
      "glum",
      "disheartened",
    ],
  },
  {
    root: "angry",
    part_of_speech: "adjective",
    context_sentence: "He was angry when he discovered the mistake.",
    synonyms: [
      "furious",
      "enraged",
      "irate",
      "incensed",
      "wrathful",
      "indignant",
      "annoyed",
      "resentful",
      "mad",
    ],
  },
  {
    root: "brave",
    part_of_speech: "adjective",
    context_sentence: "She showed great bravery in the face of danger.",
    synonyms: [
      "courageous",
      "fearless",
      "valiant",
      "bold",
      "heroic",
      "daring",
      "intrepid",
      "gallant",
      "resolute",
    ],
  },
  {
    root: "beautiful",
    part_of_speech: "adjective",
    context_sentence:
      "The sunset was so beautiful that it took her breath away.",
    synonyms: [
      "lovely",
      "stunning",
      "gorgeous",
      "attractive",
      "charming",
      "elegant",
      "exquisite",
      "captivating",
      "pretty",
    ],
  },
  {
    root: "ugly",
    part_of_speech: "adjective",
    context_sentence: "The old building was ugly and dilapidated.",
    synonyms: [
      "unattractive",
      "hideous",
      "repulsive",
      "unsightly",
      "grotesque",
      "homely",
      "plain",
      "unappealing",
      "revolting",
    ],
  },
  {
    root: "tired",
    part_of_speech: "adjective",
    context_sentence:
      "After a long day of work, she felt too tired to cook dinner.",
    synonyms: [
      "exhausted",
      "fatigued",
      "weary",
      "drained",
      "spent",
      "worn out",
      "sleepy",
      "drowsy",
      "lethargic",
    ],
  },
  {
    root: "excited",
    part_of_speech: "adjective",
    context_sentence: "He was excited about the upcoming vacation.",
    synonyms: [
      "thrilled",
      "enthusiastic",
      "eager",
      "pumped",
      "animated",
      "exhilarated",
      "elated",
      "ecstatic",
      "stirred",
    ],
  },
  {
    root: "confused",
    part_of_speech: "adjective",
    context_sentence: "She was confused by the conflicting information.",
    synonyms: [
      "bewildered",
      "perplexed",
      "disoriented",
      "puzzled",
      "baffled",
      "befuddled",
      "muddled",
      "discombobulated",
      "dazed",
    ],
  },
  {
    root: "crazy",
    part_of_speech: "adjective",
    context_sentence: "His crazy antics always made everyone laugh.",
    synonyms: [
      "insane",
      "mad",
      "lunatic",
      "bonkers",
      "deranged",
      "nutty",
      "unhinged",
      "wacky",
      "eccentric",
    ],
  },
  {
    root: "funny",
    part_of_speech: "adjective",
    context_sentence: "The funny movie had everyone laughing.",
    synonyms: [
      "humorous",
      "amusing",
      "comical",
      "hilarious",
      "entertaining",
      "lighthearted",
      "whimsical",
      "witty",
      "jocular",
    ],
  },
];
